//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneNote.WFRP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneNote.WFRP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFRP.
        /// </summary>
        internal static string AddInTitle {
            get {
                return ResourceManager.GetString("AddInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brasspenny {
            get {
                object obj = ResourceManager.GetObject("brasspenny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross_question {
            get {
                object obj = ResourceManager.GetObject("cross_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cross1 {
            get {
                object obj = ResourceManager.GetObject("cross1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon crown {
            get {
                object obj = ResourceManager.GetObject("crown", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d10 {
            get {
                object obj = ResourceManager.GetObject("d10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d10_outline {
            get {
                object obj = ResourceManager.GetObject("d10_outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d100 {
            get {
                object obj = ResourceManager.GetObject("d100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap female {
            get {
                object obj = ResourceManager.GetObject("female", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001-002 Abbie
        ///003-004 Abighild
        ///005-006 Abigund(a)
        ///007-008 Ada
        ///009-010 Adel(heid)
        ///011-012 Adelind
        ///013-014 Adelle
        ///015-016 Adelyn
        ///017-018 Agathe
        ///019-020 Agnes
        ///021-022 Agnet(h)a
        ///023-024 Agnet(h)e
        ///025-026 Agnetta
        ///027-028 Agnetz
        ///029-030 Agnise
        ///031-032 Aldreda
        ///033-034 Aleid
        ///035-036 Alette
        ///037-038 Alexa
        ///039-040 Alfreda
        ///041-042 Alfrida
        ///043-044 Alice
        ///045-046 Alicia
        ///047-048 Alke
        ///049-050 Allane
        ///051-052 Almala
        ///053-054 Althea
        ///055-056 Alusch
        ///057-058 Amali(nd)e
        ///059-060 Amalyn
        ///061-062 Andrea
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string female_forenames {
            get {
                return ResourceManager.GetString("female_forenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goldcrown {
            get {
                object obj = ResourceManager.GetObject("goldcrown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap male {
            get {
                object obj = ResourceManager.GetObject("male", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001 Abelhard(t)
        ///002 Abelheim
        ///003 Adam
        ///004 Adel(bert)
        ///005 Adelhard
        ///006 Adelmann
        ///007 Admund
        ///008 Adolf
        ///009 Adolph(us)
        ///010 Adred
        ///011 Adric
        ///012 Agilward
        ///013 Agis
        ///014 Al(d)ric 
        ///015 Alard
        ///016 Alaric
        ///017 Alberic(h)
        ///018 Albert
        ///019 Albrecht
        ///020 Aldebrand(t)
        ///021 Aldfreid
        ///022 Aldheim
        ///023 Aldred
        ///024 Alex(ander)
        ///025 Alexei
        ///026 Alexis
        ///027 Alfr(i)ed
        ///028 Alfricht
        ///029 Aloysis
        ///030 Altmar
        ///031 Anderlin
        ///032 Anders
        ///033 Andirke
        ///034 Andre(d)
        ///035 Andreas
        ///036 Andric
        ///037 Andris
        ///038 Ans(h)elm
        ///039 A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string male_forenames {
            get {
                return ResourceManager.GetString("male_forenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; loadImage=&quot;GetImage&quot;&gt;
        ///    &lt;ribbon&gt;
        ///        &lt;tabs&gt;
        ///            &lt;tab id=&quot;tabWFRP&quot; label=&quot;WFRP&quot;&gt;
        ///                &lt;group id=&quot;Dice&quot; label=&quot;Dice&quot;&gt;
        ///                  &lt;button id=&quot;d100Button&quot; label=&quot;d100&quot; size=&quot;large&quot; screentip=&quot;Roll a d100&quot; onAction=&quot;rollD100&quot; image=&quot;d100.png&quot;/&gt;
        ///                  &lt;button id=&quot;d10Button&quot; label=&quot;d10&quot; size=&quot;large&quot; screentip=&quot;Roll a d10&quot; onAction=&quot;rollD10&quot; image=&quot;d10.png&quot;/&gt;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ribbon {
            get {
                return ResourceManager.GetString("ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap silvershilling {
            get {
                object obj = ResourceManager.GetObject("silvershilling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap surname {
            get {
                object obj = ResourceManager.GetObject("surname", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001 A(h)ren
        ///002 Ad(l)
        ///003 Agbeit
        ///004 Agil
        ///005 Ahlen
        ///006 Ahr
        ///007 Al
        ///008 Al(ar)d
        ///009 Alb
        ///010 Algir
        ///011 Alp
        ///012 Alt
        ///013 Am(mil)
        ///014 An
        ///015 And
        ///016 Andre
        ///017 Ard
        ///018 Arn
        ///019 Arnulf
        ///020 Arsh
        ///021 Art(h)ur
        ///022 Asch
        ///023 Aschaf
        ///024 Atz
        ///025 Au(kru)g
        ///026 Auer
        ///027 Auf
        ///028 Aul
        ///029 Aus
        ///030 Aut
        ///031 Av
        ///032 Baak
        ///033 Bach
        ///034 Back
        ///035 Bad
        ///036 Bae(h)r(n)
        ///037 Bahr
        ///038 Bald(ur)
        ///039 Balt(h)asar
        ///040 Baltz
        ///041 Bar(t)(k)
        ///042 Bard(t)
        ///043 Barf
        ///044 Baum
        ///045 Be(h)t
        ///046 Be(i)s
        ///047 Bech
        ///048  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surname_prefix {
            get {
                return ResourceManager.GetString("surname_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 -(l)ing
        ///02 -(p)fahr(er)
        ///03 -(p)fel(s)
        ///04 -(p)feld(er)
        ///05 -(p)feller
        ///06 -(p)fen(s)
        ///07 -(s)dottir
        ///08 -(s)sen
        ///09 -as / -us
        ///10 -au(ch)
        ///11 -bach(er)
        ///12 -bad
        ///13 -bart
        ///14 -baum(er)
        ///15 -beck(er)
        ///16 -berg(er)
        ///17 -boch(er)
        ///18 -bock(er)
        ///19 -borg
        ///20 -born
        ///21 -brand(t)
        ///22 -bruck
        ///23 -burg(h)(er)
        ///24 -dorf(er)
        ///25 -e(l) / -elm
        ///26 -en
        ///27 -er(t)
        ///28 -fahre / -fer
        ///29 -fluss(er)
        ///30 -fred
        ///31 -fri(e)d
        ///32 -furt(er)
        ///33 -gang(er)
        ///34 -gart(er)
        ///35 -hafen(er)
        ///36 -ham(mer)
        ///37 -hard(t)
        ///38 -hau(s)(er [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surname_suffix {
            get {
                return ResourceManager.GetString("surname_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001 Adel, -hard, -hof(fer), -mann
        ///002 Adler(mann)
        ///003 Adolphus
        ///004 Agbeit(-en)
        ///005 Ahlen, -heim(er), -hof(fer)
        ///006 Ahresdorf(-er)
        ///007 Albrecht
        ///008 Alder(mann)
        ///009 Alexander
        ///010 Algir, -s(s)en, -sohn
        ///011 Allen(stag)
        ///012 Alp, -er(mann), -mann, -traum
        ///013 Alt, -haus(en), mann
        ///014 Altdorf, -er, -mann
        ///015 Anders, -(s)en, -sohn
        ///016 Ansel, -dorf(er), -mann
        ///017 Ardlich, -mann, -stein
        ///018 Aren, -berg(er)
        ///019 Arsch, -el(mann), -mann
        ///020 Art(h)ur, -mann
        ///021 Aschaffen, -berg(er)
        ///022 Aschen, -dorf(e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surnames {
            get {
                return ResourceManager.GetString("surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp_cross {
            get {
                object obj = ResourceManager.GetObject("xp_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
